#!/usr/bin/env python
import os
from subprocess import check_output


def _cut_useles(files):
    file_list = []
    files = files.split('\n')
    for i in range(len(files)):
        if not files[i].startswith('?'):
            files[i] = files[i][1:]
            files[i] = files[i].strip(' ')
            file_list.append(files[i])
    return file_list


p = os.popen('git status --porcelain')
files = p.read()
files = _cut_useles(files)
files.remove('')
for i in range(len(files)):
    file = files[i]
    files[i] = os.path.abspath(files[i])
    files[i] = files[i].replace('\\', '/')
    print(file)
    if i == (len(files)-1):
        str_comment_perc = check_output(["Comments_Count.bat", files[i], "DEL"])
    else:
        str_comment_perc = check_output(["Comments_Count.bat", files[i], "0"])
    perc = str_comment_perc.decode()
    perc = perc.strip('\n\r')
    if float(perc) < 30:
        print("Nel file: " + file + " i commenti sono meno del 30%")
        print('Percentuale commenti: ' + perc)
        exit(1)
    else:
        print('Nel file: ' + file + ' hai commentato bene, bravo')
        print('Percentuale commenti: ' + perc + '%')
exit(0)
